-- PROPAGATE :: Phase 8 :: 09_validation.sql
-- Consolidated validation scorecard — all section-I metrics in one table.
-- Metrics: chain reconstruction precision/recall/F1 (reconstructed chain edges vs GROUND_TRUTH_EDGES),
-- evidence coverage, false-link rate, earliest-signal detection, historical replay accuracy.
-- Chains map to ground-truth chains via their root (EVT_SC_<from_id> of the is_root GT edge).

CREATE OR REPLACE TABLE PROPAGATE.ANALYTICS.VALIDATION_METRICS AS
WITH cm AS (
  SELECT c.chain_id, g.chain_label
  FROM PROPAGATE.ANALYTICS.CHAINS c
  JOIN PROPAGATE.ANALYTICS.GROUND_TRUTH_EDGES g ON g.is_root AND ('EVT_SC_'||g.from_id)=c.root_event
),
gtrel AS (SELECT DISTINCT chain_label, relation FROM PROPAGATE.ANALYTICS.GROUND_TRUTH_EDGES),
ce AS (
  SELECT e.chain_id, e.relation, e.from_event, e.to_event, cm.chain_label,
    IFF(EXISTS(SELECT 1 FROM gtrel r WHERE r.chain_label=cm.chain_label AND r.relation=e.relation)
        AND e.from_event NOT LIKE '%-D%' AND e.to_event NOT LIKE '%-D%',1,0) AS is_tp
  FROM PROPAGATE.ANALYTICS.CHAIN_EDGES e JOIN cm ON cm.chain_id=e.chain_id
),
recon AS (
  SELECT SUM(is_tp) tp, COUNT(*) te, COUNT(*)-SUM(is_tp) fp,
         (SELECT COUNT(*) FROM gtrel WHERE chain_label IN (SELECT chain_label FROM cm)) gt_total,
         COUNT(DISTINCT CASE WHEN is_tp=1 THEN chain_label||'|'||relation END) matched_rel
  FROM ce
),
cov AS (
  SELECT AVG(IFF(((se.comp_temporal>0.1)::int+(se.comp_structural>0.1)::int+(se.comp_magnitude>0.1)::int
                 +(se.comp_textual>0.1)::int+(se.comp_historical>0.1)::int)>=2,1,0))*100 cov_pct
  FROM PROPAGATE.ANALYTICS.CHAIN_EDGES c JOIN PROPAGATE.ANALYTICS.SCORED_EDGES se ON se.edge_id=c.edge_id
),
fl AS (
  SELECT 100.0*SUM(IFF(from_event LIKE '%-D%' OR to_event LIKE '%-D%'
                       OR shared_entity_id IN ('WH-EAST','SUP-BETA','east'),1,0))/NULLIF(COUNT(*),0) flr
  FROM PROPAGATE.ANALYTICS.SCORED_EDGES WHERE retained
),
sig AS (
  SELECT SUM(IFF(c.root_event='EVT_SC_'||g.from_id,1,0)) hits, COUNT(*) tot
  FROM PROPAGATE.ANALYTICS.CHAINS c JOIN cm ON cm.chain_id=c.chain_id
  JOIN PROPAGATE.ANALYTICS.GROUND_TRUTH_EDGES g ON g.chain_label=cm.chain_label AND g.is_root
),
replay AS (
  SELECT SUM(IFF(rel_ct=6 AND fp_ct=0 AND root_ok,1,0)) hits, COUNT(*) tot FROM (
    SELECT ce.chain_label, COUNT(DISTINCT ce.relation) rel_ct,
           SUM(IFF(ce.from_event LIKE '%-D%' OR ce.to_event LIKE '%-D%',1,0)) fp_ct,
           MAX(IFF(c.root_event='EVT_SC_'||g.from_id,TRUE,FALSE)) root_ok
    FROM ce JOIN PROPAGATE.ANALYTICS.CHAINS c ON c.chain_id=ce.chain_id
    JOIN PROPAGATE.ANALYTICS.GROUND_TRUTH_EDGES g ON g.chain_label=ce.chain_label AND g.is_root
    WHERE ce.chain_label LIKE 'HIST%' GROUP BY ce.chain_label)
),
raw AS (
  SELECT r.tp, r.fp, r.te, r.gt_total, r.matched_rel,
         r.tp/NULLIF(r.te,0) AS prec, r.matched_rel/NULLIF(r.gt_total,0) AS rec,
         cov.cov_pct, fl.flr, sig.hits sig_hits, sig.tot sig_tot,
         replay.hits rep_hits, replay.tot rep_tot,
         (SELECT COUNT(*) FROM PROPAGATE.ANALYTICS.CHAINS) n_chains,
         (SELECT COUNT(*) FROM PROPAGATE.ANALYTICS.CANDIDATE_EDGES) n_cand,
         (SELECT COUNT(*) FROM PROPAGATE.ANALYTICS.SCORED_EDGES WHERE retained) n_ret
  FROM recon r, cov, fl, sig, replay
)
SELECT 'chains_reconstructed' AS metric, n_chains::float AS value, n_chains::string AS detail FROM raw
UNION ALL SELECT 'chain_reconstruction_precision', ROUND(prec,3), (tp||'/'||te||' edges') FROM raw
UNION ALL SELECT 'chain_reconstruction_recall', ROUND(rec,3), (matched_rel||'/'||gt_total||' true relations') FROM raw
UNION ALL SELECT 'chain_reconstruction_f1', ROUND(2*prec*rec/NULLIF(prec+rec,0),3), 'harmonic mean' FROM raw
UNION ALL SELECT 'evidence_coverage_pct', ROUND(cov_pct,1), 'chain edges with >=2 evidence components' FROM raw
UNION ALL SELECT 'false_link_rate_pct', ROUND(flr,1), 'retained edges touching distractor entities' FROM raw
UNION ALL SELECT 'earliest_signal_detection', ROUND(sig_hits/NULLIF(sig_tot,0),3), (sig_hits||'/'||sig_tot||' chains root-matched') FROM raw
UNION ALL SELECT 'historical_replay_accuracy', ROUND(rep_hits/NULLIF(rep_tot,0),3), (rep_hits||'/'||rep_tot||' historical chains replayed') FROM raw
UNION ALL SELECT 'candidate_edges', n_cand::float, 'generated by linker' FROM raw
UNION ALL SELECT 'retained_edges', n_ret::float, 'after evidence scoring' FROM raw;
