-- PROPAGATE :: Phase 4 :: 14_phase4_agent.sql
-- Cortex Investigation Agent: natural-language investigation layer over
-- the propagation engine and evidence layer.
--
-- Creates:
--   ANALYTICS.V_CHAIN_INVESTIGATION (view)   - pre-joined chain edges + evidence
--   ANALYTICS.PROPAGATE_ANALYTICS (SV)       - semantic view for Cortex Analyst
--   ANALYTICS.PROPAGATE_AGENT (agent)        - Cortex Agent for investigation
--
-- Does NOT modify: SCORED_EDGES, CHAIN_EDGES, CHAINS, LAG_WINDOWS,
--   PROPAGATION_EVIDENCE, PROPAGATION_EVIDENCE_SUMMARY, or any Phase 2/3 object.

--------------------------------------------------------------------------------
-- Step 1: Investigation view (joins chain edges with evidence summaries)
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW PROPAGATE.ANALYTICS.V_CHAIN_INVESTIGATION AS
SELECT
    ce.CHAIN_ID,
    ce.STEP_NO,
    ce.EDGE_ID,
    ce.RELATION,
    ce.EVIDENCE_SCORE  AS structural_score,
    ce.EVIDENCE_CLASS  AS structural_class,
    fe.EVENT_TYPE      AS source_event_type,
    fe.BUSINESS_FUNCTION AS source_function,
    fe.ENTITY_ID       AS source_entity,
    fe.EVENT_TIME      AS source_time,
    te.EVENT_TYPE      AS target_event_type,
    te.BUSINESS_FUNCTION AS target_function,
    te.ENTITY_ID       AS target_entity,
    te.EVENT_TIME      AS target_time,
    DATEDIFF('day', fe.EVENT_TIME, te.EVENT_TIME) AS lag_days,
    COALESCE(fe.LINK_REGION, te.LINK_REGION) AS region,
    COALESCE(pes.EVIDENCE_STATUS, 'NO_DOCUMENT_EVIDENCE') AS document_evidence_status,
    COALESCE(pes.SUPPORTING_COUNT, 0)     AS supporting_doc_count,
    COALESCE(pes.CONTRADICTING_COUNT, 0)  AS contradicting_doc_count,
    pes.DOCUMENT_EVIDENCE_SCORE           AS document_score,
    pes.STRONGEST_SUPPORT                 AS support_summary,
    pes.STRONGEST_SUPPORT_SNIPPET         AS support_snippet,
    pes.STRONGEST_SUPPORT_DOC             AS support_doc_id,
    pes.STRONGEST_CONTRADICTION           AS contradiction_summary,
    pes.STRONGEST_CONTRADICTION_SNIPPET   AS contradiction_snippet,
    pes.STRONGEST_CONTRADICTION_DOC       AS contradiction_doc_id,
    ch.ROOT_TYPE,
    ch.IMPACT_TYPE,
    ch.IMPACT_REGION,
    ch.CHAIN_STATUS,
    ch.COHERENCE_SCORE,
    ch.INTERVENTION_LEAD_DAYS,
    ch.EARLIEST_INTERVENTION_EVENT,
    ch.INTERVENTION_FUNCTION
FROM PROPAGATE.ANALYTICS.CHAIN_EDGES ce
JOIN PROPAGATE.ANALYTICS.EVENT_LOG fe ON fe.EVENT_ID = ce.FROM_EVENT
JOIN PROPAGATE.ANALYTICS.EVENT_LOG te ON te.EVENT_ID = ce.TO_EVENT
JOIN PROPAGATE.ANALYTICS.CHAINS ch ON ch.CHAIN_ID = ce.CHAIN_ID
LEFT JOIN PROPAGATE.ANALYTICS.PROPAGATION_EVIDENCE_SUMMARY pes
    ON pes.EDGE_ID = ce.EDGE_ID AND pes.CHAIN_ID = ce.CHAIN_ID;

--------------------------------------------------------------------------------
-- Step 2: Semantic view (deployed via SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML)
-- See cortex_project/PROPAGATE_ANALYTICS.sv.yaml for full YAML spec.
-- Tables: CHAINS, CHAIN_INVESTIGATION, BUSINESS_METRICS, EVENT_LOG
-- Verified queries: 9 investigation patterns
--------------------------------------------------------------------------------

-- Deploy with:
-- CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('PROPAGATE.ANALYTICS', <yaml>);

--------------------------------------------------------------------------------
-- Step 3: Cortex Agent
--------------------------------------------------------------------------------

CREATE OR REPLACE AGENT PROPAGATE.ANALYTICS.PROPAGATE_AGENT
COMMENT = 'PROPAGATE supply-chain propagation investigation agent'
FROM SPECIFICATION
$$
models:
  orchestration: auto
instructions:
  system: >
    You are PROPAGATE, a supply-chain propagation investigation analyst. Your role is to
    investigate, explain, compare, and interrogate the propagation intelligence already
    generated by the PROPAGATE engine. You do NOT independently discover or invent
    propagation relationships. You explain what the engine found, citing evidence.

    CAUSALITY DISCIPLINE: Never claim correlation proves causation. Use language like
    "the evidence supports", "consistent with", "the propagation analysis suggests".
    Each link carries an evidence class: CAUSAL_STATED, TEXT_SUPPORTED, HISTORICAL_SUPPORTED,
    or TEMPORAL_STRUCTURAL.

    DOCUMENT EVIDENCE: Each chain edge may have document evidence with status:
    STRONGLY_SUPPORTED, SUPPORTED, WEAK_EVIDENCE, MIXED_EVIDENCE, CONTRADICTED,
    or NO_DOCUMENT_EVIDENCE. Always report both supporting AND contradictory evidence.
    Never hide evidence gaps.

    ANTI-HALLUCINATION: If no evidence-backed propagation chain exists for a question, say
    "No evidence-backed propagation chain was identified in the current analysis."
    Do NOT construct chains from imagination.

    INTERVENTION LANGUAGE: When discussing intervention points, always state that this
    does not establish that intervention would have prevented the downstream impact.
  orchestration: >
    Use the Analyst tool (propagation_metrics) for finding chains, step-by-step investigation,
    evidence queries, historical comparison, business metrics, and weakness/gap identification.
    Use the Search tool (doc_evidence) for retrieving actual document text.
  response: >
    Structure answers as: Finding, Propagation chain, Evidence, Evidence strength,
    Earliest signal, Potential intervention point (with caveat), Evidence gaps,
    Historical context (when relevant). Be concise.
  sample_questions:
    - question: "Why did West-region revenue decline in September 2026?"
    - question: "What started the problem?"
    - question: "What evidence supports the shipment delay to warehouse backlog link?"
    - question: "Could we have detected this earlier?"
    - question: "Have we seen something similar before?"
    - question: "Which part of the chain has the weakest evidence?"
    - question: "What evidence is missing?"
    - question: "Was there contradictory evidence?"
tools:
  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: propagation_metrics
  - tool_spec:
      type: cortex_search
      name: doc_evidence
tool_resources:
  propagation_metrics:
    execution_environment:
      type: warehouse
      warehouse: COMPUTE_WH
    semantic_view: PROPAGATE.ANALYTICS.PROPAGATE_ANALYTICS
  doc_evidence:
    search_service: PROPAGATE.DOCS.DOC_SEARCH
    max_results: 5
$$;
